### ISSUE TITLE
Show better error when zone name isn't found

### ISSUE THREAD

**Issue by NixerTheFox** [prplecake/ddns-bunny.net#74]
the program pulls ipv6 and stops of errors
![image](https://github.com/user-attachments/assets/b01bc5e1-9584-466c-becd-40a0c3345b59)

plus the ip that gets pulled isn't even right...?

**Comment by NixerTheFox** [comment]
am just stupid af, i made an error in the name of the zone name and disableing ipv6 on my lan settings then it works

**Comment by prplecake** [comment]
Glad you got it solved. I'm going to reopen this to track showing a better error message for this situation.
